version: '2.3'
  integration-test:
    image: openjdk:8-jre
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - COURSIER_CACHE=/root/.coursier_cache
    volumes:
      - ./app-backend/:/opt/raster-foundry/app-backend/
      - ./.sbt:/root/.sbt
      - ./.bintray:/root/.bintray
      - $HOME/.coursier:/root/.coursier
      - $HOME/.ivy2:/root/.ivy2
    working_dir: /opt/raster-foundry/app-backend/
    depends_on:
      backsplash:
        condition: service_healthy
      api-server:
        condition: service_healthy
    entrypoint: ./sbt
    command: ["backsplash/gatling-it:test"]
