import scala.util.Properties

import sbt._

object Version {
  val akka = "2.5.16"
  val akkaCirceJson = "1.22.0"
  val akkaHttp = "10.1.5"
  val akkaHttpCors = "0.2.2"
  val akkaSlf4j = "2.4.13"
  val apacheAvro = "1.8.2"
  val apacheCommonsEmail = "1.5"
  val apacheHttpClient = "4.5.5"
  val apacheHttpCore = "4.4.9"
  val auth0 = "1.5.0"
  val awsBatchSdk = "1.11.535"
  val awsCoreSdk = "1.11.535"
  val awsLambdaCore = "1.1.0"
  val awsLambdaSdk = "1.11.535"
  val awsSdkVersion = "1.11.535"
  val awsSdkV2Version = "2.7.32"
  val awsXrayRecorder = "2.3.0"
  val betterFiles = "3.4.0"
  val caffeine = "2.3.5"
  val cats = "2.1.1"
  val catsEffect = "2.0.0"
  val catsMeow = "0.4.0"
  val catsScalacheck = "0.2.0"
  val chronoscala = "0.3.0"
  val circe = "0.12.2"
  val circeOptics = "0.12.0"
  val commonsCodec = "1.10"
  val commonsIO = "2.6"
  val cron4s = "0.6.0"
  val decline = "0.6.0"
  val dnsJava = "2.1.8"
  val doobie = "0.8.0"
  val dropbox = "3.0.9"
  val elasticacheClient = "1.1.1"
  val ficus = "1.4.0"
  val flyway = "5.2.4"
  val fs2 = "2.3.0"
  val fs2Cron = "0.2.2"
  val geotrellis = "3.3.0"
  val geotrellisContrib = "3.16.1-M3"
  val geotrellisServer = "3.4.0-9-geeb1ede-SNAPSHOT"
  val guava = "20.0"
  val hadoop = "2.8.4"
  val hikariCP = "3.3.1"
  val http4s = "0.21.3"
  val jaegerClient = "1.0.0"
  val jaegerCore = "1.0.0"
  val javaMail = "1.5.6"
  val json4s = "3.5.0"
  val jsonSmart = "2.3"
  val jts = "1.16.1"
  val log4cats = "1.0.1"
  val logback = "1.2.3"
  val maml = "0.4.0"
  val monocle = "2.0.4"
  val newtype = "0.4.3"
  val nimbusJose = "0.6.0"
  val nimbusJoseJwt = "4.41.1"
  val openTracing = "0.0.6"
  val opentracingApi = "0.33.0"
  val postgis = "2.2.1"
  val postgres = "42.2.5"
  val refined = "0.9.13"
  val rollbar = "1.4.0"
  val scaffeine = "2.6.0"
  val scala = "2.12.10"
  val scalaCheck = "1.14.0"
  val scalaCsv = "1.3.6"
  val scalaLogging = "3.9.0"
  val scalaTest = "3.0.1"
  val scalaXml = "1.2.0"
  val scalacache = "0.28.0"
  val scalajHttp = "2.4.1"
  val scapegoat = "1.3.7"
  val scopt = "3.5.0"
  val slf4j = "1.7.25"
  val sourceCode = "0.1.5"
  val spark = "2.4.2"
  val spatial4j = "0.7"
  val spire = "0.16.0"
  val spireMath = "0.13.0"
  val spray = "1.3.4"
  val sttp = "1.5.19"
  val sup = "0.6.0"
  val typesafeConfig = "1.3.3"
  val vault = "1.0.0"
}

object Dependencies {
  val akkaActor = "com.typesafe.akka" %% "akka-actor" % Version.akka
  val akkaCirceJson = "de.heikoseeberger" %% "akka-http-circe" % Version.akkaCirceJson
  val akkaHttp = "com.typesafe.akka" %% "akka-http" % Version.akkaHttp
  val akkaHttpCore = "com.typesafe.akka" %% "akka-http-core" % Version.akkaHttp
  val akkaHttpCors = "ch.megard" %% "akka-http-cors" % Version.akkaHttpCors
  val akkaSlf4j = "com.typesafe.akka" %% "akka-slf4j" % Version.akkaSlf4j % Runtime
  val akkaStream = "com.typesafe.akka" %% "akka-stream" % Version.akka
  val akkatestkit = "com.typesafe.akka" %% "akka-http-testkit" % Version.akkaHttp
  val apacheAvro = "org.apache.avro" % "avro" % Version.apacheAvro
  val apacheCommonsEmail = "org.apache.commons" % "commons-email" % Version.apacheCommonsEmail
  val apacheHttpClient = "org.apache.httpcomponents" % "httpclient" % Version.apacheHttpClient
  val apacheHttpCore = "org.apache.httpcomponents" % "httpcore" % Version.apacheHttpCore
  val auth0 = "com.auth0" % "auth0" % Version.auth0
  val awsBatchSdk = "com.amazonaws" % "aws-java-sdk-batch" % Version.awsBatchSdk
  val awsCoreSdk = "com.amazonaws" % "aws-java-sdk-core" % Version.awsCoreSdk
  val awsLambdaCore = "com.amazonaws" % "aws-lambda-java-core" % Version.awsLambdaCore
  val awsS3 = "com.amazonaws" % "aws-java-sdk-s3" % Version.awsSdkVersion
  val awsStsSdk = "com.amazonaws" % "aws-java-sdk-sts" % Version.awsSdkVersion
  val awsXrayRecorder = "com.amazonaws" % "aws-xray-recorder-sdk-core" % Version.awsXrayRecorder
  val awsXraySdk = "com.amazonaws" % "aws-java-sdk-xray" % Version.awsSdkVersion
  val awsS3SdkV2 = "software.amazon.awssdk" % "s3" % Version.awsSdkV2Version
  val awsUtilsSdkV2 = "software.amazon.awssdk" % "utils" % Version.awsSdkV2Version
  val betterFiles = "com.github.pathikrit" %% "better-files" % Version.betterFiles
  val caffeine = "com.github.ben-manes.caffeine" % "caffeine" % Version.caffeine
  val catsCore = "org.typelevel" %% "cats-core" % Version.cats
  val catsEffect = "org.typelevel" %% "cats-effect" % Version.catsEffect
  val catsFree = "org.typelevel" %% "cats-free" % Version.cats
  val catsKernel = "org.typelevel" %% "cats-kernel" % Version.cats
  val catsLaws = "org.typelevel" %% "cats-laws" % Version.cats % Test
  val catsMeow = "com.olegpy" %% "meow-mtl" % Version.catsMeow
  val catsScalacheck = "io.chrisdavenport" %% "cats-scalacheck" % Version.catsScalacheck % "test"
  val chronoscala = "jp.ne.opt" %% "chronoscala" % Version.chronoscala
  val circeCore = "io.circe" %% "circe-core" % Version.circe
  val circeGeneric = "io.circe" %% "circe-generic" % Version.circe
  val circeGenericExtras = "io.circe" %% "circe-generic-extras" % Version.circe
  val circeOptics = "io.circe" %% "circe-optics" % Version.circeOptics
  val circeParser = "io.circe" %% "circe-parser" % Version.circe
  val circeShapes = "io.circe" %% "circe-shapes" % Version.circe
  val circeTest = "io.circe" %% "circe-testing" % Version.circe % "test"
  val clistCore = "org.backuity.clist" %% "clist-core" % "3.5.0"
  val clistMacros = "org.backuity.clist" %% "clist-macros" % "3.5.0"
  val commonsCodec = "commons-codec" % "commons-codec" % Version.commonsCodec
  val commonsIO = "commons-io" % "commons-io" % Version.commonsIO
  val cron4s = "com.github.alonsodomin.cron4s" %% "cron4s-core" % Version.cron4s
  val decline = "com.monovore" %% "decline" % Version.decline
  val doobieCore = "org.tpolecat" %% "doobie-core" % Version.doobie
  val doobieFree = "org.tpolecat" %% "doobie-free" % Version.doobie
  val doobieHikari = "org.tpolecat" %% "doobie-hikari" % Version.doobie
  val doobiePostgres = "org.tpolecat" %% "doobie-postgres" % Version.doobie
  val doobiePostgresCirce = "org.tpolecat" %% "doobie-postgres-circe" % Version.doobie
  val doobieScalatest = "org.tpolecat" %% "doobie-scalatest" % Version.doobie
  val doobieSpecs = "org.tpolecat" %% "doobie-specs2" % Version.doobie
  val dropbox = "com.dropbox.core" % "dropbox-core-sdk" % Version.dropbox
  val elasticacheClient = "com.amazonaws" % "elasticache-java-cluster-client" % Version.elasticacheClient
  val ficus = "com.iheart" %% "ficus" % Version.ficus
  val flyway = "org.flywaydb" % "flyway-core" % Version.flyway
  val fs2 = "co.fs2" %% "fs2-core" % Version.fs2
  val fs2Cron = "eu.timepit" %% "fs2-cron-core" % Version.fs2Cron
  val geotrellisContribGDAL = "com.azavea.geotrellis" %% "geotrellis-contrib-gdal" % Version.geotrellisContrib
  val geotrellisContribVLM = "com.azavea.geotrellis" %% "geotrellis-contrib-vlm" % Version.geotrellisContrib
  val geotrellisProj4 = "org.locationtech.geotrellis" %% "geotrellis-proj4" % Version.geotrellis
  val geotrellisRaster = "org.locationtech.geotrellis" %% "geotrellis-raster" % Version.geotrellis
  val geotrellisS3 = "org.locationtech.geotrellis" %% "geotrellis-s3" % Version.geotrellis
  val geotrellisServer = "com.azavea.geotrellis" %% "geotrellis-server-core" % Version.geotrellisServer
  val geotrellisServerOgc = "com.azavea.geotrellis" %% "geotrellis-server-ogc" % Version.geotrellisServer
  val geotrellisServerOpenGIS = "com.azavea.geotrellis" %% "geotrellis-server-opengis" % Version.geotrellisServer
  val geotrellisServerStac = "com.azavea.geotrellis" %% "geotrellis-server-stac" % Version.geotrellisServer
  val geotrellisSpark = "org.locationtech.geotrellis" %% "geotrellis-spark" % Version.geotrellis
  val geotrellisUtil = "org.locationtech.geotrellis" %% "geotrellis-util" % Version.geotrellis
  val geotrellisVector = "org.locationtech.geotrellis" %% "geotrellis-vector" % Version.geotrellis
  val geotrellisVectorTestkit = "org.locationtech.geotrellis" %% "geotrellis-vector-testkit" % Version.geotrellis % "test"
  val guava = "com.google.guava" % "guava" % Version.guava
  val hadoop = "org.apache.hadoop" % "hadoop-common" % Version.hadoop
  val hikariCP = "com.zaxxer" % "HikariCP" % Version.hikariCP
  val http4sBlaze = "org.http4s" %% "http4s-blaze-server" % Version.http4s
  val http4sBlazeClient = "org.http4s" %% "http4s-blaze-client" % Version.http4s
  val http4sCirce = "org.http4s" %% "http4s-circe" % Version.http4s
  val http4sCore = "org.http4s" %% "http4s-core" % Version.http4s
  val http4sDSL = "org.http4s" %% "http4s-dsl" % Version.http4s
  val http4sServer = "org.http4s" %% "http4s-server" % Version.http4s
  val http4sXml = "org.http4s" %% "http4s-scala-xml" % Version.http4s
  val jaegerClient = "io.jaegertracing" % "jaeger-client" % "1.0.0"
  val jaegerCore = "io.jaegertracing" % "jaeger-core" % Version.jaegerCore
  val javaMail = "com.sun.mail" % "javax.mail" % Version.javaMail
  val jsonSmart = "net.minidev" % "json-smart" % Version.jsonSmart
  val jts = "org.locationtech.jts" % "jts-core" % Version.jts
  val log4cats = "io.chrisdavenport" %% "log4cats-core" % Version.log4cats
  val log4catsSlf4j = "io.chrisdavenport" %% "log4cats-slf4j" % Version.log4cats
  val log4jOverslf4j = "org.slf4j" % "slf4j-simple" % Version.slf4j
  val logbackClassic = "ch.qos.logback" % "logback-classic" % Version.logback
  val mamlJvm = "com.azavea.geotrellis" %% "maml-jvm" % Version.maml
  val monocleCore = "com.github.julien-truffaut" %% "monocle-core" % Version.monocle
  val newtype = "io.estatico" %% "newtype" % Version.newtype
  val nimbusJose = "com.guizmaii" %% "scala-nimbus-jose-jwt" % Version.nimbusJose
  val nimbusJoseJwt = "com.nimbusds" % "nimbus-jose-jwt" % Version.nimbusJoseJwt
  val opentracing = "com.colisweb" %% "scala-opentracing" % Version.openTracing
  val opentracingApi = "io.opentracing" % "opentracing-api" % Version.opentracingApi
  val postgis = "net.postgis" % "postgis-jdbc" % Version.postgis
  val postgres = "org.postgresql" % "postgresql" % Version.postgres
  val refined = "eu.timepit" %% "refined" % Version.refined
  val rollbar = "com.rollbar" % "rollbar-java" % Version.rollbar
  val scaffeine = "com.github.blemale" %% "scaffeine" % Version.scaffeine
  val scalaCheck = "org.scalacheck" %% "scalacheck" % Version.scalaCheck % "test"
  val scalaLogging = "com.typesafe.scala-logging" %% "scala-logging" % Version.scalaLogging
  val scalaXml = "org.scala-lang.modules" %% "scala-xml" % Version.scalaXml
  val scalacacheCaffeine = "com.github.cb372" %% "scalacache-caffeine" % Version.scalacache
  val scalacacheCats = "com.github.cb372" %% "scalacache-cats-effect" % Version.scalacache
  val scalacacheCirce = "com.github.cb372" %% "scalacache-circe" % Version.scalacache
  val scalacacheCore = "com.github.cb372" %% "scalacache-core" % Version.scalacache
  val scalacacheMemcached = "com.github.cb372" %% "scalacache-memcached" % Version.scalacache intransitive ()
  val scalaCsv = "com.github.tototoshi" %% "scala-csv" % Version.scalaCsv
  val scalajHttp = "org.scalaj" %% "scalaj-http" % Version.scalajHttp
  val scalatest = "org.scalatest" %% "scalatest" % Version.scalaTest % "test"
  val scopt = "com.github.scopt" %% "scopt" % Version.scopt
  val shapeless = "com.chuusai" %% "shapeless" % "2.3.3"
  val slf4j = "org.slf4j" % "slf4j-api" % Version.slf4j
  val sourceCode = "com.lihaoyi" %% "sourcecode" % Version.sourceCode
  val spark = "org.apache.spark" %% "spark-core" % Version.spark % "provided"
  val sparkCore = "org.apache.spark" %% "spark-core" % Version.spark
  val spatial4j = "org.locationtech.spatial4j" % "spatial4j" % Version.spatial4j
  val spire = "org.typelevel" %% "spire" % Version.spire
  val spireMath = "org.spire-math" %% "spire" % Version.spireMath
  val spray = "io.spray" %% "spray-json" % Version.spray
  val sttpCatsBackend = "com.softwaremill.sttp" %% "async-http-client-backend-cats" % Version.sttp
  val sttpCirce = "com.softwaremill.sttp" %% "circe" % Version.sttp
  val sttpCore = "com.softwaremill.sttp" %% "core" % Version.sttp
  val sttpJson = "com.softwaremill.sttp" %% "json-common" % Version.sttp
  val sttpOkHttpBackend = "com.softwaremill.sttp" %% "okhttp-backend" % Version.sttp
  val sup = "com.kubukoz" %% "sup-core" % Version.sup
  val typesafeConfig = "com.typesafe" % "config" % Version.typesafeConfig
  val vault = "io.chrisdavenport" %% "vault" % Version.vault
}
