object Version {
  val rasterFoundry      = "0.1"

  val akka               = "2.4.3"
  val geotrellis         = "0.10.2"
  val hikariCP           = "3.1.1"
  val postgres           = "9.4-1201-jdbc41"
  val scala              = "2.11.8"
  val scalaForklift      = "0.2.2"
  val scalaTest          = "2.2.6"
  val scapegoat          = "1.2.0"
  val slf4j              = "1.6.4"
  val slick              = "3.1.1"
  val slickPG            = "0.14.3"
  val sprayjson          = "2.4.4"
  val akkaAuth           = "0.2.0"
  val akkaHttpExtensions = "0.4.8"
  val akkaHttpCors       = "0.1.6"
  val ammoniteOps        = "0.7.0"
  val spark              = "2.0.0"
  val aws                = "1.9.34"
}
