FROM nginx:1.20.0-alpine

RUN mkdir -p /nginx/etc/nginx/includes

COPY /static /srv/dist/
RUN chown nginx:nginx -R /srv/dist/

COPY /nginx/etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /nginx/etc/nginx/includes/*.conf /etc/nginx/includes/
COPY /nginx/etc/nginx/templates/default.conf.template /etc/nginx/templates/default.conf.template
