FROM nginx:1.20.0-alpine

RUN mkdir -p /etc/nginx/includes

COPY /srv/dist/ /srv/dist/
RUN chown nginx:nginx -R /srv/dist/

COPY ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./etc/nginx/includes/*.conf /etc/nginx/includes/
COPY ./etc/nginx/templates/api.conf.template /etc/nginx/templates/default.conf.template
