- name: Configure Collectd plugins
  template: src={{ item }}.conf.j2 dest=/etc/collectd/collectd.conf.d/{{ item }}.conf
  with_items:
    - apache
    - filecount
    - memcached
    - syslog
    - tail
    - write_graphite
  notify:
    - Restart Collectd
