import slick.jdbc.PostgresProfile.api._
import com.liyaos.forklift.slick.SqlMigration

object M99 {
  RFMigrations.migrations = RFMigrations.migrations :+ SqlMigration(99)(
    List(
      sqlu"""
    INSERT INTO licenses (
      short_name, name, url, osi_approved
    ) VALUES
    ('0BSD', 'BSD Zero Clause License', 'http://landley.net/toybox/license.html', FALSE),
    ('AAL', 'Attribution Assurance License', 'http://www.opensource.org/licenses/attribution', TRUE),
    ('Abstyles', 'Abstyles License', 'https://fedoraproject.org/wiki/Licensing/Abstyles', FALSE),
    ('Adobe-2006', 'Adobe Systems Incorporated Source Code License Agreement', 'https://fedoraproject.org/wiki/Licensing/AdobeLicense', FALSE),
    ('Adobe-Glyph', 'Adobe Glyph List License', 'https://fedoraproject.org/wiki/Licensing/MIT#AdobeGlyph', FALSE),
    ('ADSL', 'Amazon Digital Services License', 'https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense', FALSE),
    ('AFL-1.1', 'Academic Free License v1.1', 'http://opensource.linux-mirror.org/licenses/afl-1.1.txt', TRUE),
    ('AFL-1.2', 'Academic Free License v1.2', 'http://opensource.linux-mirror.org/licenses/afl-1.2.txt', TRUE),
    ('AFL-2.0', 'Academic Free License v2.0', 'http://opensource.linux-mirror.org/licenses/afl-2.0.txt', TRUE),
    ('AFL-2.1', 'Academic Free License v2.1', 'http://opensource.linux-mirror.org/licenses/afl-2.1.txt', TRUE),
    ('AFL-3.0', 'Academic Free License v3.0', 'http://www.rosenlaw.com/AFL3.0.htm', TRUE),
    ('Afmparse', 'Afmparse License', 'https://fedoraproject.org/wiki/Licensing/Afmparse', FALSE),
    ('AGPL-1.0', 'Affero General Public License v1.0', 'http://www.affero.org/oagpl.html', FALSE),
    ('AGPL-3.0-only', 'GNU Affero General Public License v3.0 only', 'http://www.gnu.org/licenses/agpl.txt', TRUE),
    ('AGPL-3.0-or-later', 'GNU Affero General Public License v3.0 or later', 'http://www.gnu.org/licenses/agpl.txt', TRUE),
    ('Aladdin', 'Aladdin Free Public License', 'http://pages.cs.wisc.edu/~ghost/doc/AFPL/6.01/Public.htm', FALSE),
    ('AMDPLPA', 'AMD''s plpa_map.c License', 'https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License', FALSE),
    ('AML', 'Apple MIT License', 'https://fedoraproject.org/wiki/Licensing/Apple_MIT_License', FALSE),
    ('AMPAS', 'Academy of Motion Picture Arts and Sciences BSD', 'https://fedoraproject.org/wiki/Licensing/BSD#AMPASBSD', FALSE),
    ('ANTLR-PD', 'ANTLR Software Rights Notice', 'http://www.antlr2.org/license.html', FALSE),
    ('Apache-1.0', 'Apache License 1.0', 'http://www.apache.org/licenses/LICENSE-1.0', FALSE),
    ('Apache-1.1', 'Apache License 1.1', 'http://apache.org/licenses/LICENSE-1.1', TRUE),
    ('Apache-2.0', 'Apache License 2.0', 'http://www.apache.org/licenses/LICENSE-2.0', TRUE),
    ('APAFML', 'Adobe Postscript AFM License', 'https://fedoraproject.org/wiki/Licensing/AdobePostscriptAFM', FALSE),
    ('APL-1.0', 'Adaptive Public License 1.0', 'http://www.opensource.org/licenses/APL-1.0', TRUE),
    ('APSL-1.0', 'Apple Public Source License 1.0', 'https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0', TRUE),
    ('APSL-1.1', 'Apple Public Source License 1.1', 'http://www.opensource.apple.com/source/IOSerialFamily/IOSerialFamily-7/APPLE_LICENSE', TRUE),
    ('APSL-1.2', 'Apple Public Source License 1.2', 'http://www.samurajdata.se/opensource/mirror/licenses/apsl.php', TRUE),
    ('APSL-2.0', 'Apple Public Source License 2.0', 'http://www.opensource.apple.com/license/apsl/', TRUE),
    ('Artistic-1.0-cl8', 'Artistic License 1.0 w/clause 8', 'http://opensource.org/licenses/Artistic-1.0', TRUE),
    ('Artistic-1.0-Perl', 'Artistic License 1.0 (Perl)', 'http://dev.perl.org/licenses/artistic.html', TRUE),
    ('Artistic-1.0', 'Artistic License 1.0', 'http://opensource.org/licenses/Artistic-1.0', TRUE),
    ('Artistic-2.0', 'Artistic License 2.0', 'http://www.perlfoundation.org/artistic_license_2_0', TRUE),
    ('Bahyph', 'Bahyph License', 'https://fedoraproject.org/wiki/Licensing/Bahyph', FALSE),
    ('Barr', 'Barr License', 'https://fedoraproject.org/wiki/Licensing/Barr', FALSE),
    ('Beerware', 'Beerware License', 'https://fedoraproject.org/wiki/Licensing/Beerware', FALSE),
    ('BitTorrent-1.0', 'BitTorrent Open Source License v1.0', 'http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s', FALSE),
    ('BitTorrent-1.1', 'BitTorrent Open Source License v1.1', 'http://directory.fsf.org/wiki/License:BitTorrentOSL1.1', FALSE),
    ('Borceux', 'Borceux license', 'https://fedoraproject.org/wiki/Licensing/Borceux', FALSE),
    ('BSD-1-Clause', 'BSD 1-Clause License', 'https://svnweb.freebsd.org/base/head/include/ifaddrs.h?revision=326823', FALSE),
    ('BSD-2-Clause-FreeBSD', 'BSD 2-Clause FreeBSD License', 'http://www.freebsd.org/copyright/freebsd-license.html', FALSE),
    ('BSD-2-Clause-NetBSD', 'BSD 2-Clause NetBSD License', 'http://www.netbsd.org/about/redistribution.html#default', FALSE),
    ('BSD-2-Clause-Patent', 'BSD-2-Clause Plus Patent License', 'https://opensource.org/licenses/BSDplusPatent', TRUE),
    ('BSD-2-Clause', 'BSD 2-Clause "Simplified" License', 'http://www.opensource.org/licenses/BSD-2-Clause', TRUE),
    ('BSD-3-Clause-Attribution', 'BSD with attribution', 'https://fedoraproject.org/wiki/Licensing/BSD_with_Attribution', FALSE),
    ('BSD-3-Clause-Clear', 'BSD 3-Clause Clear License', 'http://labs.metacarta.com/license-explanation.html#license', FALSE),
    ('BSD-3-Clause-LBNL', 'Lawrence Berkeley National Labs BSD variant license', 'https://fedoraproject.org/wiki/Licensing/LBNLBSD', FALSE),
    ('BSD-3-Clause-No-Nuclear-License-2014', 'BSD 3-Clause No Nuclear License 2014', 'https://java.net/projects/javaeetutorial/pages/BerkeleyLicense', FALSE),
    ('BSD-3-Clause-No-Nuclear-License', 'BSD 3-Clause No Nuclear License', 'http://download.oracle.com/otn-pub/java/licenses/bsd.txt?AuthParam=1467140197_43d516ce1776bd08a58235a7785be1cc', FALSE),
    ('BSD-3-Clause-No-Nuclear-Warranty', 'BSD 3-Clause No Nuclear Warranty', 'https://jogamp.org/git/?p=gluegen.git;a=blob_plain;f=LICENSE.txt', FALSE),
    ('BSD-3-Clause', 'BSD 3-Clause "New" or "Revised" License', 'http://www.opensource.org/licenses/BSD-3-Clause', TRUE),
    ('BSD-4-Clause-UC', 'BSD-4-Clause (University of California-Specific)', 'http://www.freebsd.org/copyright/license.html', FALSE),
    ('BSD-4-Clause', 'BSD 4-Clause "Original" or "Old" License', 'http://directory.fsf.org/wiki/License:BSD_4Clause', FALSE),
    ('BSD-Protection', 'BSD Protection License', 'https://fedoraproject.org/wiki/Licensing/BSD_Protection_License', FALSE),
    ('BSD-Source-Code', 'BSD Source Code Attribution', 'https://github.com/robbiehanson/CocoaHTTPServer/blob/master/LICENSE.txt', FALSE),
    ('BSL-1.0', 'Boost Software License 1.0', 'http://www.boost.org/LICENSE_1_0.txt', TRUE),
    ('bzip2-1.0.5', 'bzip2 and libbzip2 License v1.0.5', 'http://bzip.org/1.0.5/bzip2-manual-1.0.5.html', FALSE),
    ('bzip2-1.0.6', 'bzip2 and libbzip2 License v1.0.6', 'https://github.com/asimonov-im/bzip2/blob/master/LICENSE', FALSE),
    ('Caldera', 'Caldera License', 'http://www.lemis.com/grog/UNIX/ancient-source-all.pdf', FALSE),
    ('CATOSL-1.1', 'Computer Associates Trusted Open Source License 1.1', 'http://opensource.org/licenses/CATOSL-1.1', TRUE),
    ('CC-BY-1.0', 'Creative Commons Attribution 1.0', 'http://creativecommons.org/licenses/by/1.0/legalcode', FALSE),
    ('CC-BY-2.0', 'Creative Commons Attribution 2.0', 'http://creativecommons.org/licenses/by/2.0/legalcode', FALSE),
    ('CC-BY-2.5', 'Creative Commons Attribution 2.5', 'http://creativecommons.org/licenses/by/2.5/legalcode', FALSE),
    ('CC-BY-3.0', 'Creative Commons Attribution 3.0', 'http://creativecommons.org/licenses/by/3.0/legalcode', FALSE),
    ('CC-BY-4.0', 'Creative Commons Attribution 4.0', 'http://creativecommons.org/licenses/by/4.0/legalcode', FALSE),
    ('CC-BY-NC-1.0', 'Creative Commons Attribution Non Commercial 1.0', 'http://creativecommons.org/licenses/by-nc/1.0/legalcode', FALSE),
    ('CC-BY-NC-2.0', 'Creative Commons Attribution Non Commercial 2.0', 'http://creativecommons.org/licenses/by-nc/2.0/legalcode', FALSE),
    ('CC-BY-NC-2.5', 'Creative Commons Attribution Non Commercial 2.5', 'http://creativecommons.org/licenses/by-nc/2.5/legalcode', FALSE),
    ('CC-BY-NC-3.0', 'Creative Commons Attribution Non Commercial 3.0', 'http://creativecommons.org/licenses/by-nc/3.0/legalcode', FALSE),
    ('CC-BY-NC-4.0', 'Creative Commons Attribution Non Commercial 4.0', 'http://creativecommons.org/licenses/by-nc/4.0/legalcode', FALSE),
    ('CC-BY-NC-ND-1.0', 'Creative Commons Attribution Non Commercial No Derivatives 1.0', 'http://creativecommons.org/licenses/by-nd-nc/1.0/legalcode', FALSE),
    ('CC-BY-NC-ND-2.0', 'Creative Commons Attribution Non Commercial No Derivatives 2.0', 'http://creativecommons.org/licenses/by-nc-nd/2.0/legalcode', FALSE),
    ('CC-BY-NC-ND-2.5', 'Creative Commons Attribution Non Commercial No Derivatives 2.5', 'http://creativecommons.org/licenses/by-nc-nd/2.5/legalcode', FALSE),
    ('CC-BY-NC-ND-3.0', 'Creative Commons Attribution Non Commercial No Derivatives 3.0', 'http://creativecommons.org/licenses/by-nc-nd/3.0/legalcode', FALSE),
    ('CC-BY-NC-ND-4.0', 'Creative Commons Attribution Non Commercial No Derivatives 4.0', 'http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode', FALSE),
    ('CC-BY-NC-SA-1.0', 'Creative Commons Attribution Non Commercial Share Alike 1.0', 'http://creativecommons.org/licenses/by-nc-sa/1.0/legalcode', FALSE),
    ('CC-BY-NC-SA-2.0', 'Creative Commons Attribution Non Commercial Share Alike 2.0', 'http://creativecommons.org/licenses/by-nc-sa/2.0/legalcode', FALSE),
    ('CC-BY-NC-SA-2.5', 'Creative Commons Attribution Non Commercial Share Alike 2.5', 'http://creativecommons.org/licenses/by-nc-sa/2.5/legalcode', FALSE),
    ('CC-BY-NC-SA-3.0', 'Creative Commons Attribution Non Commercial Share Alike 3.0', 'http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode', FALSE),
    ('CC-BY-NC-SA-4.0', 'Creative Commons Attribution Non Commercial Share Alike 4.0', 'http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode', FALSE),
    ('CC-BY-ND-1.0', 'Creative Commons Attribution No Derivatives 1.0', 'http://creativecommons.org/licenses/by-nd/1.0/legalcode', FALSE),
    ('CC-BY-ND-2.0', 'Creative Commons Attribution No Derivatives 2.0', 'https://creativecommons.org/licenses/by-nd/2.0/legalcode', FALSE),
    ('CC-BY-ND-2.5', 'Creative Commons Attribution No Derivatives 2.5', 'http://creativecommons.org/licenses/by-nd/2.5/legalcode', FALSE),
    ('CC-BY-ND-3.0', 'Creative Commons Attribution No Derivatives 3.0', 'http://creativecommons.org/licenses/by-nd/3.0/legalcode', FALSE),
    ('CC-BY-ND-4.0', 'Creative Commons Attribution No Derivatives 4.0', 'http://creativecommons.org/licenses/by-nd/4.0/legalcode', FALSE),
    ('CC-BY-SA-1.0', 'Creative Commons Attribution Share Alike 1.0', 'http://creativecommons.org/licenses/by-sa/1.0/legalcode', FALSE),
    ('CC-BY-SA-2.0', 'Creative Commons Attribution Share Alike 2.0', 'http://creativecommons.org/licenses/by-sa/2.0/legalcode', FALSE),
    ('CC-BY-SA-2.5', 'Creative Commons Attribution Share Alike 2.5', 'http://creativecommons.org/licenses/by-sa/2.5/legalcode', FALSE),
    ('CC-BY-SA-3.0', 'Creative Commons Attribution Share Alike 3.0', 'http://creativecommons.org/licenses/by-sa/3.0/legalcode', FALSE),
    ('CC-BY-SA-4.0', 'Creative Commons Attribution Share Alike 4.0', 'http://creativecommons.org/licenses/by-sa/4.0/legalcode', FALSE),
    ('CC0-1.0', 'Creative Commons Zero v1.0 Universal', 'http://creativecommons.org/publicdomain/zero/1.0/legalcode', FALSE),
    ('CDDL-1.0', 'Common Development and Distribution License 1.0', 'http://www.opensource.org/licenses/cddl1', TRUE),
    ('CDDL-1.1', 'Common Development and Distribution License 1.1', 'http://glassfish.java.net/public/CDDL+GPL_1_1.html', FALSE),
    ('CDLA-Permissive-1.0', 'Community Data License Agreement Permissive 1.0', 'https://cdla.io/permissive-1-0', FALSE),
    ('CDLA-Sharing-1.0', 'Community Data License Agreement Sharing 1.0', 'https://cdla.io/sharing-1-0', FALSE),
    ('CECILL-1.0', 'CeCILL Free Software License Agreement v1.0', 'http://www.cecill.info/licences/Licence_CeCILL_V1-fr.html', FALSE),
    ('CECILL-1.1', 'CeCILL Free Software License Agreement v1.1', 'http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html', FALSE),
    ('CECILL-2.0', 'CeCILL Free Software License Agreement v2.0', 'http://www.cecill.info/licences/Licence_CeCILL_V2-en.html', FALSE),
    ('CECILL-2.1', 'CeCILL Free Software License Agreement v2.1', 'http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html', TRUE),
    ('CECILL-B', 'CeCILL-B Free Software License Agreement', 'http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html', FALSE),
    ('CECILL-C', 'CeCILL-C Free Software License Agreement', 'http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html\n', FALSE),
    ('ClArtistic', 'Clarified Artistic License', 'http://gianluca.dellavedova.org/2011/01/03/clarified-artistic-license/', FALSE),
    ('CNRI-Jython', 'CNRI Jython License', 'http://www.jython.org/license.html', FALSE),
    ('CNRI-Python-GPL-Compatible', 'CNRI Python Open Source GPL Compatible License Agreement', 'http://www.python.org/download/releases/1.6.1/download_win/', FALSE),
    ('CNRI-Python', 'CNRI Python License', 'http://www.opensource.org/licenses/CNRI-Python', TRUE),
    ('Condor-1.1', 'Condor Public License v1.1', 'http://research.cs.wisc.edu/condor/license.html#condor', FALSE),
    ('CPAL-1.0', 'Common Public Attribution License 1.0', 'http://www.opensource.org/licenses/CPAL-1.0', TRUE),
    ('CPL-1.0', 'Common Public License 1.0', 'http://opensource.org/licenses/CPL-1.0', TRUE),
    ('CPOL-1.02', 'Code Project Open License 1.02', 'http://www.codeproject.com/info/cpol10.aspx', FALSE),
    ('Crossword', 'Crossword License', 'https://fedoraproject.org/wiki/Licensing/Crossword', FALSE),
    ('CrystalStacker', 'CrystalStacker License', 'https://fedoraproject.org/wiki/Licensing:CrystalStacker?rd=Licensing/CrystalStacker', FALSE),
    ('CUA-OPL-1.0', 'CUA Office Public License v1.0', 'http://opensource.org/licenses/CUA-OPL-1.0', TRUE),
    ('Cube', 'Cube License', 'https://fedoraproject.org/wiki/Licensing/Cube', FALSE),
    ('curl', 'curl License', 'https://github.com/bagder/curl/blob/master/COPYING', FALSE),
    ('D-FSL-1.0', 'Deutsche Freie Software Lizenz', 'http://www.dipp.nrw.de/d-fsl/lizenzen/', FALSE),
    ('diffmark', 'diffmark license', 'https://fedoraproject.org/wiki/Licensing/diffmark', FALSE),
    ('DOC', 'DOC License', 'http://www.cs.wustl.edu/~schmidt/ACE-copying.html', FALSE),
    ('Dotseqn', 'Dotseqn License', 'https://fedoraproject.org/wiki/Licensing/Dotseqn', FALSE),
    ('DSDP', 'DSDP License', 'https://fedoraproject.org/wiki/Licensing/DSDP', FALSE),
    ('dvipdfm', 'dvipdfm License', 'https://fedoraproject.org/wiki/Licensing/dvipdfm', FALSE),
    ('ECL-1.0', 'Educational Community License v1.0', 'http://opensource.org/licenses/ECL-1.0', TRUE),
    ('ECL-2.0', 'Educational Community License v2.0', 'http://opensource.org/licenses/ECL-2.0', TRUE),
    ('EFL-1.0', 'Eiffel Forum License v1.0', 'http://www.eiffel-nice.org/license/forum.txt', TRUE),
    ('EFL-2.0', 'Eiffel Forum License v2.0', 'http://www.eiffel-nice.org/license/eiffel-forum-license-2.html', TRUE),
    ('eGenix', 'eGenix.com Public License 1.1.0', 'http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf', FALSE),
    ('Entessa', 'Entessa Public License v1.0', 'http://opensource.org/licenses/Entessa', TRUE),
    ('EPL-1.0', 'Eclipse Public License 1.0', 'http://www.eclipse.org/legal/epl-v10.html', TRUE),
    ('EPL-2.0', 'Eclipse Public License 2.0', 'https://www.eclipse.org/legal/epl-2.0', TRUE),
    ('ErlPL-1.1', 'Erlang Public License v1.1', 'http://www.erlang.org/EPLICENSE', FALSE),
    ('EUDatagrid', 'EU DataGrid Software License', 'http://eu-datagrid.web.cern.ch/eu-datagrid/license.html', TRUE),
    ('EUPL-1.0', 'European Union Public License 1.0', 'http://ec.europa.eu/idabc/en/document/7330.html', FALSE),
    ('EUPL-1.1', 'European Union Public License 1.1', 'https://joinup.ec.europa.eu/software/page/eupl/licence-eupl', TRUE),
    ('EUPL-1.2', 'European Union Public License 1.2', 'https://joinup.ec.europa.eu/page/eupl-text-11-12', TRUE),
    ('Eurosym', 'Eurosym License', 'https://fedoraproject.org/wiki/Licensing/Eurosym', FALSE),
    ('Fair', 'Fair License', 'http://www.opensource.org/licenses/Fair', TRUE),
    ('Frameworx-1.0', 'Frameworx Open License 1.0', 'http://www.opensource.org/licenses/Frameworx-1.0', TRUE),
    ('FreeImage', 'FreeImage Public License v1.0', 'http://freeimage.sourceforge.net/freeimage-license.txt', FALSE),
    ('FSFAP', 'FSF All Permissive License', 'http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html', FALSE),
    ('FSFUL', 'FSF Unlimited License', 'https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License', FALSE),
    ('FSFULLR', 'FSF Unlimited License (with License Retention)', 'https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant', FALSE),
    ('FTL', 'Freetype Project License', 'http://freetype.fis.uniroma2.it/FTL.TXT', FALSE),
    ('GFDL-1.1-only', 'GNU Free Documentation License v1.1 only', 'http://www.gnu.org/licenses/old-licenses/fdl-1.1.txt', FALSE),
    ('GFDL-1.1-or-later', 'GNU Free Documentation License v1.1 or later', 'http://www.gnu.org/licenses/old-licenses/fdl-1.1.txt', FALSE),
    ('GFDL-1.2-only', 'GNU Free Documentation License v1.2 only', 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.txt', FALSE),
    ('GFDL-1.2-or-later', 'GNU Free Documentation License v1.2 or later', 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.txt', FALSE),
    ('GFDL-1.3-only', 'GNU Free Documentation License v1.3 only', 'http://www.gnu.org/licenses/fdl-1.3.txt', FALSE),
    ('GFDL-1.3-or-later', 'GNU Free Documentation License v1.3 or later', 'http://www.gnu.org/licenses/fdl-1.3.txt', FALSE),
    ('Giftware', 'Giftware License', 'http://liballeg.org/license.html#allegro-4-the-giftware-license', FALSE),
    ('GL2PS', 'GL2PS License', 'http://www.geuz.org/gl2ps/COPYING.GL2PS', FALSE),
    ('Glide', '3dfx Glide License', 'http://www.users.on.net/~triforce/glidexp/COPYING.txt', FALSE),
    ('Glulxe', 'Glulxe License', 'https://fedoraproject.org/wiki/Licensing/Glulxe', FALSE),
    ('gnuplot', 'gnuplot License', 'https://fedoraproject.org/wiki/Licensing/Gnuplot', FALSE),
    ('GPL-1.0-only', 'GNU General Public License v1.0 only', 'http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html', FALSE),
    ('GPL-1.0-or-later', 'GNU General Public License v1.0 or later', 'http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html', FALSE),
    ('GPL-2.0-only', 'GNU General Public License v2.0 only', 'http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html', TRUE),
    ('GPL-2.0-or-later', 'GNU General Public License v2.0 or later', 'http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html', TRUE),
    ('GPL-3.0-only', 'GNU General Public License v3.0 only', 'http://www.gnu.org/licenses/gpl-3.0-standalone.html', TRUE),
    ('GPL-3.0-or-later', 'GNU General Public License v3.0 or later', 'http://www.gnu.org/licenses/gpl-3.0-standalone.html', TRUE),
    ('gSOAP-1.3b', 'gSOAP Public License v1.3b', 'http://www.cs.fsu.edu/~engelen/license.html', FALSE),
    ('HaskellReport', 'Haskell Language Report License', 'https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License', FALSE),
    ('HPND', 'Historical Permission Notice and Disclaimer', 'http://www.opensource.org/licenses/HPND', TRUE),
    ('IBM-pibs', 'IBM PowerPC Initialization and Boot Software', 'http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d', FALSE),
    ('ICU', 'ICU License', 'http://source.icu-project.org/repos/icu/icu/trunk/license.html', FALSE),
    ('IJG', 'Independent JPEG Group License', 'http://dev.w3.org/cvsweb/Amaya/libjpeg/Attic/README?rev=1.2', FALSE),
    ('ImageMagick', 'ImageMagick License', 'http://www.imagemagick.org/script/license.php', FALSE),
    ('iMatix', 'iMatix Standard Function Library Agreement', 'http://legacy.imatix.com/html/sfl/sfl4.htm#license', FALSE),
    ('Imlib2', 'Imlib2 License', 'https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING', FALSE),
    ('Info-ZIP', 'Info-ZIP License', 'http://www.info-zip.org/license.html', FALSE),
    ('Intel-ACPI', 'Intel ACPI Software License Agreement', 'https://fedoraproject.org/wiki/Licensing/Intel_ACPI_Software_License_Agreement', FALSE),
    ('Intel', 'Intel Open Source License', 'http://opensource.org/licenses/Intel', TRUE),
    ('Interbase-1.0', 'Interbase Public License v1.0', 'https://web.archive.org/web/20060319014854/http://info.borland.com/devsupport/interbase/opensource/IPL.html', FALSE),
    ('IPA', 'IPA Font License', 'http://www.opensource.org/licenses/IPA', TRUE),
    ('IPL-1.0', 'IBM Public License v1.0', 'http://www.opensource.org/licenses/IPL-1.0', TRUE),
    ('ISC', 'ISC License', 'https://www.isc.org/downloads/software-support-policy/isc-license/', TRUE),
    ('JasPer-2.0', 'JasPer License', 'http://www.ece.uvic.ca/~mdadams/jasper/LICENSE', FALSE),
    ('JSON', 'JSON License', 'http://www.json.org/license.html', FALSE),
    ('LAL-1.2', 'Licence Art Libre 1.2', 'http://artlibre.org/licence/lal/licence-art-libre-12/', FALSE),
    ('LAL-1.3', 'Licence Art Libre 1.3', 'http://artlibre.org/', FALSE),
    ('Latex2e', 'Latex2e License', 'https://fedoraproject.org/wiki/Licensing/Latex2e', FALSE),
    ('Leptonica', 'Leptonica License', 'https://fedoraproject.org/wiki/Licensing/Leptonica', FALSE),
    ('LGPL-2.0-only', 'GNU Library General Public License v2 only', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html', TRUE),
    ('LGPL-2.0-or-later', 'GNU Library General Public License v2 or later', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html', TRUE),
    ('LGPL-2.1-only', 'GNU Lesser General Public License v2.1 only', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html', TRUE),
    ('LGPL-2.1-or-later', 'GNU Lesser General Public License v2.1 or later', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html', TRUE),
    ('LGPL-3.0-only', 'GNU Lesser General Public License v3.0 only', 'http://www.gnu.org/licenses/lgpl-3.0-standalone.html', TRUE),
    ('LGPL-3.0-or-later', 'GNU Lesser General Public License v3.0 or later', 'http://www.gnu.org/licenses/lgpl-3.0-standalone.html', TRUE),
    ('LGPLLR', 'Lesser General Public License For Linguistic Resources', 'http://www-igm.univ-mlv.fr/~unitex/lgpllr.html', FALSE),
    ('Libpng', 'libpng License', 'http://www.libpng.org/pub/png/src/libpng-LICENSE.txt', FALSE),
    ('libtiff', 'libtiff License', 'https://fedoraproject.org/wiki/Licensing/libtiff', FALSE),
    ('LiLiQ-P-1.1', 'Licence Libre du Québec – Permissive version 1.1', 'http://opensource.org/licenses/LiLiQ-P-1.1', TRUE),
    ('LiLiQ-R-1.1', 'Licence Libre du Québec – Réciprocité version 1.1', 'http://opensource.org/licenses/LiLiQ-R-1.1', TRUE),
    ('LiLiQ-Rplus-1.1', 'Licence Libre du Québec – Réciprocité forte version 1.1', 'http://opensource.org/licenses/LiLiQ-Rplus-1.1', TRUE),
    ('LPL-1.0', 'Lucent Public License Version 1.0', 'http://opensource.org/licenses/LPL-1.0', TRUE),
    ('LPL-1.02', 'Lucent Public License v1.02', 'http://plan9.bell-labs.com/plan9/license.html', TRUE),
    ('LPPL-1.0', 'LaTeX Project Public License v1.0', 'http://www.latex-project.org/lppl/lppl-1-0.txt', FALSE),
    ('LPPL-1.1', 'LaTeX Project Public License v1.1', 'http://www.latex-project.org/lppl/lppl-1-1.txt', FALSE),
    ('LPPL-1.2', 'LaTeX Project Public License v1.2', 'http://www.latex-project.org/lppl/lppl-1-2.txt', FALSE),
    ('LPPL-1.3a', 'LaTeX Project Public License v1.3a', 'http://www.latex-project.org/lppl/lppl-1-3a.txt', FALSE),
    ('LPPL-1.3c', 'LaTeX Project Public License v1.3c', 'http://www.latex-project.org/lppl/lppl-1-3c.txt', TRUE),
    ('MakeIndex', 'MakeIndex License', 'https://fedoraproject.org/wiki/Licensing/MakeIndex', FALSE),
    ('MirOS', 'MirOS License', 'http://www.opensource.org/licenses/MirOS', TRUE),
    ('MIT-advertising', 'Enlightenment License (e16)', 'https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising', FALSE),
    ('MIT-CMU', 'CMU License', 'https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#CMU_Style', FALSE),
    ('MIT-enna', 'enna License', 'https://fedoraproject.org/wiki/Licensing/MIT#enna', FALSE),
    ('MIT-feh', 'feh License', 'https://fedoraproject.org/wiki/Licensing/MIT#feh', FALSE),
    ('MIT', 'MIT License', 'http://www.opensource.org/licenses/MIT', TRUE),
    ('MITNFA', 'MIT +no-false-attribs license', 'https://fedoraproject.org/wiki/Licensing/MITNFA', FALSE),
    ('Motosoto', 'Motosoto License', 'http://www.opensource.org/licenses/Motosoto', TRUE),
    ('mpich2', 'mpich2 License', 'https://fedoraproject.org/wiki/Licensing/MIT', FALSE),
    ('MPL-1.0', 'Mozilla Public License 1.0', 'http://www.mozilla.org/MPL/MPL-1.0.html', TRUE),
    ('MPL-1.1', 'Mozilla Public License 1.1', 'http://www.mozilla.org/MPL/MPL-1.1.html', TRUE),
    ('MPL-2.0-no-copyleft-exception', 'Mozilla Public License 2.0 (no copyleft exception)', 'http://www.mozilla.org/MPL/2.0/', TRUE),
    ('MPL-2.0', 'Mozilla Public License 2.0', 'http://www.mozilla.org/MPL/2.0/', TRUE),
    ('MS-PL', 'Microsoft Public License', 'http://www.microsoft.com/opensource/licenses.mspx', TRUE),
    ('MS-RL', 'Microsoft Reciprocal License', 'http://www.microsoft.com/opensource/licenses.mspx', TRUE),
    ('MTLL', 'Matrix Template Library License', 'https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License', FALSE),
    ('Multics', 'Multics License', 'http://www.opensource.org/licenses/Multics', TRUE),
    ('Mup', 'Mup License', 'https://fedoraproject.org/wiki/Licensing/Mup', FALSE),
    ('NASA-1.3', 'NASA Open Source Agreement 1.3', 'http://ti.arc.nasa.gov/opensource/nosa/', TRUE),
    ('Naumen', 'Naumen Public License', 'http://www.opensource.org/licenses/Naumen', TRUE),
    ('NBPL-1.0', 'Net Boolean Public License v1', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=37b4b3f6cc4bf34e1d3dec61e69914b9819d8894', FALSE),
    ('NCSA', 'University of Illinois/NCSA Open Source License', 'http://otm.illinois.edu/uiuc_openSource', TRUE),
    ('Net-SNMP', 'Net-SNMP License', 'http://net-snmp.sourceforge.net/about/license.html', FALSE),
    ('NetCDF', 'NetCDF license', 'http://www.unidata.ucar.edu/software/netcdf/copyright.html', FALSE),
    ('Newsletr', 'Newsletr License', 'https://fedoraproject.org/wiki/Licensing/Newsletr', FALSE),
    ('NGPL', 'Nethack General Public License', 'http://www.opensource.org/licenses/NGPL', TRUE),
    ('NLOD-1.0', 'Norwegian Licence for Open Government Data', 'http://data.norge.no/nlod/en/1.0', FALSE),
    ('NLPL', 'No Limit Public License', 'https://fedoraproject.org/wiki/Licensing/NLPL', FALSE),
    ('Nokia', 'Nokia Open Source License', 'http://www.opensource.org/licenses/nokia', TRUE),
    ('NOSL', 'Netizen Open Source License', 'http://bits.netizen.com.au/licenses/NOSL/nosl.txt', FALSE),
    ('Noweb', 'Noweb License', 'https://fedoraproject.org/wiki/Licensing/Noweb', FALSE),
    ('NPL-1.0', 'Netscape Public License v1.0', 'http://www.mozilla.org/MPL/NPL/1.0/', FALSE),
    ('NPL-1.1', 'Netscape Public License v1.1', 'http://www.mozilla.org/MPL/NPL/1.1/', FALSE),
    ('NPOSL-3.0', 'Non-Profit Open Software License 3.0', 'http://www.opensource.org/licenses/NOSL3.0', TRUE),
    ('NRL', 'NRL License', 'http://web.mit.edu/network/isakmp/nrllicense.html', FALSE),
    ('NTP', 'NTP License', 'http://www.opensource.org/licenses/NTP', TRUE),
    ('OCCT-PL', 'Open CASCADE Technology Public License', 'http://www.opencascade.com/content/occt-public-license', FALSE),
    ('OCLC-2.0', 'OCLC Research Public License 2.0', 'http://www.oclc.org/research/activities/software/license/v2final.htm', TRUE),
    ('ODbL-1.0', 'ODC Open Database License v1.0', 'http://www.opendatacommons.org/licenses/odbl/1.0/', FALSE),
    ('OFL-1.0', 'SIL Open Font License 1.0', 'http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web', FALSE),
    ('OFL-1.1', 'SIL Open Font License 1.1', 'http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web', TRUE),
    ('OGTSL', 'Open Group Test Suite License', 'http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt', TRUE),
    ('OLDAP-1.1', 'Open LDAP Public License v1.1', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=806557a5ad59804ef3a44d5abfbe91d706b0791f', FALSE),
    ('OLDAP-1.2', 'Open LDAP Public License v1.2', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=42b0383c50c299977b5893ee695cf4e486fb0dc7', FALSE),
    ('OLDAP-1.3', 'Open LDAP Public License v1.3', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=e5f8117f0ce088d0bd7a8e18ddf37eaa40eb09b1', FALSE),
    ('OLDAP-1.4', 'Open LDAP Public License v1.4', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=c9f95c2f3f2ffb5e0ae55fe7388af75547660941', FALSE),
    ('OLDAP-2.0.1', 'Open LDAP Public License v2.0.1', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e', FALSE),
    ('OLDAP-2.0', 'Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cbf50f4e1185a21abd4c0a54d3f4341fe28f36ea', FALSE),
    ('OLDAP-2.1', 'Open LDAP Public License v2.1', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715', FALSE),
    ('OLDAP-2.2.1', 'Open LDAP Public License v2.2.1', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=4bc786f34b50aa301be6f5600f58a980070f481e', FALSE),
    ('OLDAP-2.2.2', 'Open LDAP Public License 2.2.2', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=df2cc1e21eb7c160695f5b7cffd6296c151ba188', FALSE),
    ('OLDAP-2.2', 'Open LDAP Public License v2.2', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=470b0c18ec67621c85881b2733057fecf4a1acc3', FALSE),
    ('OLDAP-2.3', 'Open LDAP Public License v2.3', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3', FALSE),
    ('OLDAP-2.4', 'Open LDAP Public License v2.4', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=cd1284c4a91a8a380d904eee68d1583f989ed386', FALSE),
    ('OLDAP-2.5', 'Open LDAP Public License v2.5', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=6852b9d90022e8593c98205413380536b1b5a7cf', FALSE),
    ('OLDAP-2.6', 'Open LDAP Public License v2.6', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=1cae062821881f41b73012ba816434897abf4205', FALSE),
    ('OLDAP-2.7', 'Open LDAP Public License v2.7', 'http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=47c2415c1df81556eeb39be6cad458ef87c534a2', FALSE),
    ('OLDAP-2.8', 'Open LDAP Public License v2.8', 'http://www.openldap.org/software/release/license.html', FALSE),
    ('OML', 'Open Market License', 'https://fedoraproject.org/wiki/Licensing/Open_Market_License', FALSE),
    ('OpenSSL', 'OpenSSL License', 'http://www.openssl.org/source/license.html', FALSE),
    ('OPL-1.0', 'Open Public License v1.0', 'http://old.koalateam.com/jackaroo/OPL_1_0.TXT', FALSE),
    ('OSET-PL-2.1', 'OSET Public License version 2.1', 'http://opensource.org/licenses/OPL-2.1', TRUE),
    ('OSL-1.0', 'Open Software License 1.0', 'http://opensource.org/licenses/OSL-1.0', TRUE),
    ('OSL-1.1', 'Open Software License 1.1', 'https://fedoraproject.org/wiki/Licensing/OSL1.1', FALSE),
    ('OSL-2.0', 'Open Software License 2.0', 'http://web.archive.org/web/20041020171434/http://www.rosenlaw.com/osl2.0.html', TRUE),
    ('OSL-2.1', 'Open Software License 2.1', 'http://opensource.org/licenses/OSL-2.1', TRUE),
    ('OSL-3.0', 'Open Software License 3.0', 'http://www.rosenlaw.com/OSL3.0.htm', TRUE),
    ('PDDL-1.0', 'ODC Public Domain Dedication & License 1.0', 'http://opendatacommons.org/licenses/pddl/1.0/', FALSE),
    ('PHP-3.0', 'PHP License v3.0', 'http://www.opensource.org/licenses/PHP-3.0', TRUE),
    ('PHP-3.01', 'PHP License v3.01', 'http://www.php.net/license/3_01.txt', FALSE),
    ('Plexus', 'Plexus Classworlds License', 'https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License', FALSE),
    ('PostgreSQL', 'PostgreSQL License', 'http://www.postgresql.org/about/licence', TRUE),
    ('psfrag', 'psfrag License', 'https://fedoraproject.org/wiki/Licensing/psfrag', FALSE),
    ('psutils', 'psutils License', 'https://fedoraproject.org/wiki/Licensing/psutils', FALSE),
    ('Python-2.0', 'Python License 2.0', 'http://www.opensource.org/licenses/Python-2.0', TRUE),
    ('Qhull', 'Qhull License', 'https://fedoraproject.org/wiki/Licensing/Qhull', FALSE),
    ('QPL-1.0', 'Q Public License 1.0', 'http://doc.qt.nokia.com/3.3/license.html', TRUE),
    ('Rdisc', 'Rdisc License', 'https://fedoraproject.org/wiki/Licensing/Rdisc_License', FALSE),
    ('RHeCos-1.1', 'Red Hat eCos Public License v1.1', 'http://ecos.sourceware.org/old-license.html', FALSE),
    ('RPL-1.1', 'Reciprocal Public License 1.1', 'http://opensource.org/licenses/RPL-1.1', TRUE),
    ('RPL-1.5', 'Reciprocal Public License 1.5', 'http://www.opensource.org/licenses/RPL-1.5', TRUE),
    ('RPSL-1.0', 'RealNetworks Public Source License v1.0', 'https://helixcommunity.org/content/rpsl', TRUE),
    ('RSA-MD', 'RSA Message-Digest License', 'http://www.faqs.org/rfcs/rfc1321.html', FALSE),
    ('RSCPL', 'Ricoh Source Code Public License', 'http://www.opensource.org/licenses/RSCPL', TRUE),
    ('Ruby', 'Ruby License', 'http://www.ruby-lang.org/en/LICENSE.txt', FALSE),
    ('SAX-PD', 'Sax Public Domain Notice', 'http://www.saxproject.org/copying.html', FALSE),
    ('Saxpath', 'Saxpath License', 'https://fedoraproject.org/wiki/Licensing/Saxpath_License', FALSE),
    ('SCEA', 'SCEA Shared Source License', 'http://research.scea.com/scea_shared_source_license.html', FALSE),
    ('Sendmail', 'Sendmail License', 'http://www.sendmail.com/pdfs/open_source/sendmail_license.pdf', FALSE),
    ('SGI-B-1.0', 'SGI Free Software License B v1.0', 'http://oss.sgi.com/projects/FreeB/SGIFreeSWLicB.1.0.html', FALSE),
    ('SGI-B-1.1', 'SGI Free Software License B v1.1', 'http://oss.sgi.com/projects/FreeB/', FALSE),
    ('SGI-B-2.0', 'SGI Free Software License B v2.0', 'http://oss.sgi.com/projects/FreeB/SGIFreeSWLicB.2.0.pdf', FALSE),
    ('SimPL-2.0', 'Simple Public License 2.0', 'http://www.opensource.org/licenses/SimPL-2.0', TRUE),
    ('SISSL-1.2', 'Sun Industry Standards Source License v1.2', 'http://gridscheduler.sourceforge.net/Gridengine_SISSL_license.html', FALSE),
    ('SISSL', 'Sun Industry Standards Source License v1.1', 'http://www.openoffice.org/licenses/sissl_license.html', TRUE),
    ('Sleepycat', 'Sleepycat License', 'http://www.opensource.org/licenses/Sleepycat', TRUE),
    ('SMLNJ', 'Standard ML of New Jersey License', 'https://www.smlnj.org/license.html', FALSE),
    ('SMPPL', 'Secure Messaging Protocol Public License', 'https://github.com/dcblake/SMP/blob/master/Documentation/License.txt', FALSE),
    ('SNIA', 'SNIA Public License 1.1', 'https://fedoraproject.org/wiki/Licensing/SNIA_Public_License', FALSE),
    ('Spencer-86', 'Spencer License 86', 'https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License', FALSE),
    ('Spencer-94', 'Spencer License 94', 'https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License', FALSE),
    ('Spencer-99', 'Spencer License 99', 'http://www.opensource.apple.com/source/tcl/tcl-5/tcl/generic/regfronts.c', FALSE),
    ('SPL-1.0', 'Sun Public License v1.0', 'http://www.opensource.org/licenses/SPL-1.0', TRUE),
    ('SugarCRM-1.1.3', 'SugarCRM Public License v1.1.3', 'http://www.sugarcrm.com/crm/SPL', FALSE),
    ('SWL', 'Scheme Widget Library (SWL) Software License Agreement', 'https://fedoraproject.org/wiki/Licensing/SWL', FALSE),
    ('TCL', 'TCL/TK License', 'http://www.tcl.tk/software/tcltk/license.html', FALSE),
    ('TCP-wrappers', 'TCP Wrappers License', 'http://rc.quest.com/topics/openssh/license.php#tcpwrappers', FALSE),
    ('TMate', 'TMate Open Source License', 'http://svnkit.com/license.html', FALSE),
    ('TORQUE-1.1', 'TORQUE v2.5+ Software License v1.1', 'https://fedoraproject.org/wiki/Licensing/TORQUEv1.1', FALSE),
    ('TOSL', 'Trusster Open Source License', 'https://fedoraproject.org/wiki/Licensing/TOSL', FALSE),
    ('Unicode-DFS-2015', 'Unicode License Agreement - Data Files and Software (2015)', 'https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html', FALSE),
    ('Unicode-DFS-2016', 'Unicode License Agreement - Data Files and Software (2016)', 'http://www.unicode.org/copyright.html', FALSE),
    ('Unicode-TOU', 'Unicode Terms of Use', 'http://www.unicode.org/copyright.html', FALSE),
    ('Unlicense', 'The Unlicense', 'http://unlicense.org/', FALSE),
    ('UPL-1.0', 'Universal Permissive License v1.0', 'http://opensource.org/licenses/UPL', TRUE),
    ('Vim', 'Vim License', 'http://vimdoc.sourceforge.net/htmldoc/uganda.html', FALSE),
    ('VOSTROM', 'VOSTROM Public License for Open Source', 'https://fedoraproject.org/wiki/Licensing/VOSTROM', FALSE),
    ('VSL-1.0', 'Vovida Software License v1.0', 'http://www.opensource.org/licenses/VSL-1.0', TRUE),
    ('W3C-19980720', 'W3C Software Notice and License (1998-07-20)', 'http://www.w3.org/Consortium/Legal/copyright-software-19980720.html', FALSE),
    ('W3C-20150513', 'W3C Software Notice and Document License (2015-05-13)', 'https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document', FALSE),
    ('W3C', 'W3C Software Notice and License (2002-12-31)', 'http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html', TRUE),
    ('Watcom-1.0', 'Sybase Open Watcom Public License 1.0', 'http://www.opensource.org/licenses/Watcom-1.0', TRUE),
    ('Wsuipa', 'Wsuipa License', 'https://fedoraproject.org/wiki/Licensing/Wsuipa', FALSE),
    ('WTFPL', 'Do What The F*ck You Want To Public License', 'http://sam.zoy.org/wtfpl/COPYING', FALSE),
    ('X11', 'X11 License', 'http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3', FALSE),
    ('Xerox', 'Xerox License', 'https://fedoraproject.org/wiki/Licensing/Xerox', FALSE),
    ('XFree86-1.1', 'XFree86 License 1.1', 'http://www.xfree86.org/current/LICENSE4.html', FALSE),
    ('xinetd', 'xinetd License', 'https://fedoraproject.org/wiki/Licensing/Xinetd_License', FALSE),
    ('Xnet', 'X.Net License', 'http://opensource.org/licenses/Xnet', TRUE),
    ('xpp', 'XPP License', 'https://fedoraproject.org/wiki/Licensing/xpp', FALSE),
    ('XSkat', 'XSkat License', 'https://fedoraproject.org/wiki/Licensing/XSkat_License', FALSE),
    ('YPL-1.0', 'Yahoo! Public License v1.0', 'http://www.zimbra.com/license/yahoo_public_license_1.0.html', FALSE),
    ('YPL-1.1', 'Yahoo! Public License v1.1', 'http://www.zimbra.com/license/yahoo_public_license_1.1.html', FALSE),
    ('Zed', 'Zed License', 'https://fedoraproject.org/wiki/Licensing/Zed', FALSE),
    ('Zend-2.0', 'Zend License v2.0', 'https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt', FALSE),
    ('Zimbra-1.3', 'Zimbra Public License v1.3', 'https://spdx.org/licenses/Zimbra-1.3.html', FALSE),
    ('Zimbra-1.4', 'Zimbra Public License v1.4', 'http://www.zimbra.com/legal/zimbra-public-license-1-4', FALSE),
    ('zlib-acknowledgement', 'zlib/libpng License with Acknowledgement', 'https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement', FALSE),
    ('Zlib', 'zlib License', 'http://www.zlib.net/zlib_license.html', TRUE),
    ('ZPL-1.1', 'Zope Public License 1.1', 'http://old.zope.org/Resources/License/ZPL-1.1', FALSE),
    ('ZPL-2.0', 'Zope Public License 2.0', 'http://old.zope.org/Resources/License/ZPL-2.0', TRUE),
    ('ZPL-2.1', 'Zope Public License 2.1', 'http://old.zope.org/Resources/ZPL/', FALSE),
    ('AGPL-3.0', 'GNU Affero General Public License v3.0', 'http://www.gnu.org/licenses/agpl.txt', TRUE),
    ('eCos-2.0', 'eCos license version 2.0', 'http://www.gnu.org/licenses/ecos-license.html', FALSE),
    ('GFDL-1.1', 'GNU Free Documentation License v1.1', 'http://www.gnu.org/licenses/old-licenses/fdl-1.1.txt', FALSE),
    ('GFDL-1.2', 'GNU Free Documentation License v1.2', 'http://www.gnu.org/licenses/old-licenses/fdl-1.2.txt', FALSE),
    ('GFDL-1.3', 'GNU Free Documentation License v1.3', 'http://www.gnu.org/licenses/fdl-1.3.txt', FALSE),
    ('GPL-1.0+', 'GNU General Public License v1.0 or later', 'http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html', FALSE),
    ('GPL-1.0', 'GNU General Public License v1.0 only', 'http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html', FALSE),
    ('GPL-2.0+', 'GNU General Public License v2.0 or later', 'http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html', TRUE),
    ('GPL-2.0-with-autoconf-exception', 'GNU General Public License v2.0 w/Autoconf exception', 'http://ac-archive.sourceforge.net/doc/copyright.html', FALSE),
    ('GPL-2.0-with-bison-exception', 'GNU General Public License v2.0 w/Bison exception', 'http://git.savannah.gnu.org/cgit/bison.git/tree/data/yacc.c?id=193d7c7054ba7197b0789e14965b739162319b5e#n141', FALSE),
    ('GPL-2.0-with-classpath-exception', 'GNU General Public License v2.0 w/Classpath exception', 'http://www.gnu.org/software/classpath/license.html', FALSE),
    ('GPL-2.0-with-font-exception', 'GNU General Public License v2.0 w/Font exception', 'http://www.gnu.org/licenses/gpl-faq.html#FontException', FALSE),
    ('GPL-2.0-with-GCC-exception', 'GNU General Public License v2.0 w/GCC Runtime Library exception', 'https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/libgcc1.c;h=762f5143fc6eed57b6797c82710f3538aa52b40b;hb=cb143a3ce4fb417c68f5fa2691a1b1b1053dfba9#l10', FALSE),
    ('GPL-2.0', 'GNU General Public License v2.0 only', 'http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html', TRUE),
    ('GPL-3.0+', 'GNU General Public License v3.0 or later', 'http://www.gnu.org/licenses/gpl-3.0-standalone.html', TRUE),
    ('GPL-3.0-with-autoconf-exception', 'GNU General Public License v3.0 w/Autoconf exception', 'http://www.gnu.org/licenses/autoconf-exception-3.0.html', FALSE),
    ('GPL-3.0-with-GCC-exception', 'GNU General Public License v3.0 w/GCC Runtime Library exception', 'http://www.gnu.org/licenses/gcc-exception-3.1.html', TRUE),
    ('GPL-3.0', 'GNU General Public License v3.0 only', 'http://www.gnu.org/licenses/gpl-3.0-standalone.html', TRUE),
    ('LGPL-2.0+', 'GNU Library General Public License v2 or later', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html', TRUE),
    ('LGPL-2.0', 'GNU Library General Public License v2 only', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.0-standalone.html', TRUE),
    ('LGPL-2.1+', 'GNU Library General Public License v2 or later', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html', TRUE),
    ('LGPL-2.1', 'GNU Lesser General Public License v2.1 only', 'http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html', TRUE),
    ('LGPL-3.0+', 'GNU Lesser General Public License v3.0 or later', 'http://www.gnu.org/licenses/lgpl-3.0-standalone.html', TRUE),
    ('LGPL-3.0', 'GNU Lesser General Public License v3.0 only', 'http://www.gnu.org/licenses/lgpl-3.0-standalone.html', TRUE),
    ('Nunit', 'Nunit License', 'https://fedoraproject.org/wiki/Licensing/Nunit', FALSE),
    ('StandardML-NJ', 'Standard ML of New Jersey License', 'http://www.smlnj.org//license.html', FALSE),
    ('wxWindows', 'wxWindows Library License', 'http://www.opensource.org/licenses/WXwindows', FALSE);
    """
    ))
}
