#!/bin/bash
set -eu

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Builds/Pulls containers for project

Example: ./scripts/bootstrap
"
}


function main() {
    echo "Building/Pulling containers..."

    # Pull images for postgres
    docker-compose \
        -f "${DIR}/../docker-compose.yml" \
        pull
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then

    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        main
    fi
    exit
fi
