#!/bin/bash
set -eu

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Builds/Pulls containers for project

Example: ./scripts/bootstrap
"
}


function main() {

    echo "Pulling down development environment..."
    pushd "${DIR}/.."
    # Download environment configuration from S3
    aws s3 cp "s3://config-development-raster-foundry/.env" ".env"
    popd

    echo "Building/Pulling containers..."
    # Pull images for postgres and scala
    docker-compose \
        -f "${DIR}/../docker-compose.yml" \
        pull

    # Build luigi scheduler image
    docker-compose \
        -f "${DIR}/../docker-compose.yml" \
        build

    # Build luigi base image
    docker-compose \
        -f "${DIR}/../pipelines/tasks/docker-compose.yml" \
        build task-worker
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then

    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        main
    fi
    exit
fi
