#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

# fail without RF_SETTINGS_BUCKET
set -u

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Bootstrap development environment.

--containers builds containers / pulls postgres and memcached
--env        pulls .env file from S3
--sbtopts    pulls .sbtopts from S3
"
}

function build_containers() {
    echo "Building containers / pulling postgres and memcached"
    pushd "${DIR}"

    docker-compose \
        -f "${DIR}/docker-compose.yml" \
        build
    docker-compose \
        -f "${DIR}/docker-compose.yml" \
        pull postgres memcached

    popd
}

function pull_env() {
    echo "Pulling .env from s3://${RF_SETTINGS_BUCKET}"
    pushd "${DIR}"

    aws s3 cp "s3://${RF_SETTINGS_BUCKET}/.env" ".env"

    popd
}

function generate_sbtopts() {
    echo "Generating .sbtopts"
    pushd "${DIR}"

    cp app-backend/.sbtopts.sample app-backend/.sbtopts

    function override_build_repos() {
        echo "Overriding repository configuration for ${1}"
        echo "-Dsbt.override.build.repos=true" >> app-backend/.sbtopts
        echo "-Dsbt.repository.config=project/${1}/repositories" >> app-backend/.sbtopts
    }

    if host nexus.internal.azavea.com; then
        override_build_repos "development"
    elif host nexus.rasterfoundry.internal; then
        override_build_repos "ci"
    fi

    sort app-backend/.sbtopts | uniq > cleaned_sbtopts
    mv cleaned_sbtopts app-backend/.sbtopts

    popd
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [ "${1:-}" = "--containers" ]; then
        build_containers
    elif [ "${1:-}" = "--env" ]; then
        pull_env
    elif [ "${1:-}" = "--sbtopts" ]; then
        generate_sbtopts
    else
        pull_env
        generate_sbtopts
        build_containers
    fi
fi
