#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build application for staging or release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Pulling down configuration settings for test environment"
        pushd "${DIR}/.."
        aws s3 cp "s3://${RF_SETTINGS_BUCKET}/.env" ".env"
        popd

        echo "Building static asset bundle"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend install
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run build

        echo "Building batch JAR"
        docker-compose \
            run --rm --no-deps api-server batch/clean
        docker-compose \
            run --rm --no-deps api-server batch/assembly

        cp "${DIR}/../app-backend/batch/target/scala-2.11/rf-batch.jar" \
           "${DIR}/../app-tasks/jars/rf-batch.jar"

        echo "Building Airflow container image"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
                  -f "${DIR}/../docker-compose.yml" \
                  -f "${DIR}/../docker-compose.airflow.yml" \
                  -f "${DIR}/../docker-compose.test.yml" \
                  build airflow airflow-worker

        echo "Running tests"
        GIT_COMMIT="${GIT_COMMIT}" ./scripts/test
        echo "All tests pass!"

        ./scripts/deploy-docs --dryrun
    fi
fi
