#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

GIT_COMMIT="${GIT_COMMIT:-latest}"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Fire gatling at a running backsplash server
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Firing gatling at staging..."
        docker run --rm \
          -v "$(pwd)/gatling:/opt/gatling" \
          -v "$HOME/.ivy2:/root/.ivy2" \
          -w /opt/gatling/ \
          -e RF_API_HOST \
          -e RF_PROJECT_ID \
          -e TOKEN_ROUTE \
          -e REFRESH_TOKEN \
          -e RANDOM_SEED \
          -e PROJECT_ROUTE \
          -e USER_COUNT \
          -e RAMPUP_TIME \
          -e BACKSPLASH_TMS_URL_TEMPLATE \
          -e MIN_ZOOM \
          -e MAX_ZOOM \
          openjdk:8-jre \
          ./sbt gatling:test || true

        echo "Uploading results to '$RESULTS_BUCKET'..."
        # Most recent report will always be last, since they're timestamped
        reportDir=$(find ./gatling/target/gatling/ -maxdepth 1 -type d | tail -n 1)
        zippedName=$(basename "$reportDir").zip
        zippedDir=$(dirname "$reportDir")
        zip -r9 "$zippedDir/$zippedName" "$reportDir"
        aws s3 cp "$zippedDir/$zippedName" "s3://$RESULTS_BUCKET/$GIT_COMMIT/"
    fi
    exit
fi

