#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Deploy Swagger spec to a S3 website bucket.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [[ -n "${RF_DOCS_BUCKET}" ]]; then
            if [ "${1:-}" = "--dryrun" ]; then
                echo "Syncing docs to ${RF_DOCS_BUCKET} (dryrun)"
                aws s3 cp --dryrun \
                    "${DIR}/../docs/swagger/spec.yml" \
                    "s3://${RF_DOCS_BUCKET}/spec/"
            else
                echo "Syncing docs to ${RF_DOCS_BUCKET}"
                aws s3 cp \
                    "${DIR}/../docs/swagger/spec.yml" \
                    "s3://${RF_DOCS_BUCKET}/spec/"
            fi
        else
            echo "ERROR: No RF_DOCS_BUCKET found."
        fi

    fi
fi
