#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0" JAR_NAME)

Publish jars to Bintray
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    fi
    
    echo "Publishing application JAR"
    docker-compose \
        run --rm --no-deps api-server api/publish
        
    echo "Publishing authentication JAR"
    docker-compose \
        run --rm --no-deps api-server api/publish
        
    echo "Publishing batch JAR"
    docker-compose \
        run --rm --no-deps api-server batch/publish
        
    echo "Publishing datamodel JAR"
    docker-compose \
        run --rm --no-deps api-server datamodel/publish
        
    echo "Publishing db JAR"
    docker-compose \
        run --rm --no-deps api-server db/publish
        
    echo "Publishing tile server JAR"
    docker-compose \
        run --rm --no-deps api-server tile/publish          
fi
