#!/bin/bash
set -eu


DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Starts servers using docker-compose
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        docker-compose -f "${DIR}/../docker-compose.yml" up \
                       app-backend \
                       nginx \
                       swagger-editor \
                       postgres \
                       airflow-worker \
                       airflow-webserver \
                       airflow-scheduler \
                       airflow-flower \
                       redis
    fi
    exit
fi
