#!/bin/bash
set -eu


DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0") [--with-airflow]

Starts servers using docker-compose
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    elif [ "${1:-}" = "--with-airflow" ]
    then
        docker-compose -f "${DIR}/../docker-compose.yml" \
                       -f "${DIR}/../docker-compose.airflow.yml" up
    elif [ "${1:-}" = "--with-metrics" ]
    then
        docker-compose -f "${DIR}/../docker-compose.yml" \
                       -f "${DIR}/../docker-compose.metrics.yml" up
    else
        docker-compose up --remove-orphans
    fi
    exit
fi
