#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Attempts to setup the project's development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Ensure that a directory exists to house AWS profiles.
        mkdir -p "${HOME}/.aws"
        mkdir -p "nginx/srv/dist/"

        vagrant up --provision
    fi
fi
