#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

GIT_COMMIT="${GIT_COMMIT:-latest}"
DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Run tests
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Lint Bash scripts
        if which shellcheck; then
            find ./scripts -not -name "*.py*" -type f -exec shellcheck {} +
        fi

        # Run linter/inspector to identify issues with app-backend
        docker-compose \
            -f "${DIR}/../docker-compose.yml" run \
            --rm \
            --entrypoint "/bin/bash -c" \
            app-backend "./sbt scapegoat"

        # Run scala tests for app-backend
       docker-compose \
           -f "${DIR}/../docker-compose.yml" run \
           --rm \
           --entrypoint "/bin/bash -c" \
           app-backend "./sbt test"

        # TODO: uncomment once https://github.com/azavea/raster-foundry/issues/435
        # is resolved
        # Run js tests for app-frontend
#       docker-compose \
#           -f "${DIR}/../docker-compose.yml" run \
#            --rm \
#            --entrypoint "/bin/bash -c" \
#            app-frontend "npm run test"

        # Run tests for app tasks library
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm --entrypoint "/bin/bash -c" airflow \
            "cd /opt/raster-foundry/app-tasks/rf && python setup.py test"
    fi
    exit
fi
