#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

GIT_COMMIT="${GIT_COMMIT:-latest}"
DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Run various test suites.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        if which shellcheck &>/dev/null; then
            echo "Linting STRTA scripts"
            find ./scripts -type f -print0 | xargs -0 -r shellcheck
        fi

        echo "Verifying that Airflow containers can run the batch jar"
        docker-compose \
            -f docker-compose.airflow.yml \
            run --rm airflow-worker \
            bash -c \
            "java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main healthcheck"

        echo "Validating swagger specification"
        docker-compose \
            -f docker-compose.test.yml \
            run --rm app-frontend \
            swagger validate /opt/swagger/spec.yml

        echo "Updating Scala dependencies"
        docker-compose \
            run --rm --no-deps api-server update

        echo "Linting Scala source code"
        docker-compose \
            run --rm --no-deps api-server scapegoat

        echo "Executing Scala test suite"
        docker-compose \
            run --rm api-server test

        # TODO: https://github.com/azavea/raster-foundry/issues/435
        # echo "Executing JavaScript test suite"
        # docker-compose \
        #     -f "${DIR}/../docker-compose.yml" \
        #     -f "${DIR}/../docker-compose.test.yml" \
        #     run --rm app-frontend run test

        echo "Executing Airflow task test suite"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" run \
            --rm \
            --entrypoint python \
            --user root \
            --workdir /opt/raster-foundry/app-tasks/rf \
            airflow setup.py test
    fi
    exit
fi
