#!/bin/bash

set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Run various test suites.
"
}

GIT_COMMIT="${GIT_COMMIT:-latest}"

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if command -v shellcheck &>/dev/null; then
            echo "Linting STRTA scripts"
            find ./scripts -type f -print0 | xargs -0 -r shellcheck
        fi

        if [ -f /opt/raster-foundry/jars/batch-assembly.jar ]; then
            echo "Verifying that Batch containers can run the batch jar"
            docker-compose \
                run --rm batch \
                bash -c \
                "java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main healthcheck"
        fi

        echo "Updating Scala dependencies"
        docker-compose \
            run --rm --no-deps sbt \
            update

        echo "Linting Scala source code"
        docker-compose \
            run --rm --no-deps sbt \
            ";scalafmtCheck;scalafmtSbtCheck;scapegoat"

        echo "Validating API service spec"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run validate-api-spec

        echo "Validating tile service spec"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run validate-tile-spec

        echo "Preparing the database for testing"
        source "scripts/update"
        run_database_migrations

        echo "Executing Scala test suite"
        docker-compose \
            run --rm sbt \
            test

    fi
fi
