#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")

Update project dependencies, build assembly JARs, run database migrations,
and build static asset bundle.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Building Scala assembly JARs"
        sbt \
            ";api/assembly;backsplash-server/assembly;batch/assembly;backsplash-export/assembly"

        echo "Running application database migrations"
        ./scripts/migrate migrate

        echo "Updating frontend dependencies"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend install

        echo "Building static asset bundle"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run build
    fi
fi
