#!/bin/bash
set -e

if [[ -n "${RF_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"


function usage() {

    echo -n \
"Usage: $(basename "$0")
Setup external project dependencies.
"
}

function run_database_migrations() {
    # Check if database migrations have already been initialized
    set +e
    docker-compose \
        exec -T postgres gosu postgres psql -d rasterfoundry -c 'select 1 from __migrations__' &>/dev/null
    status_check=$?
    set -e
    if [ $status_check == 0 ]
    then
        echo "Migrations already initialized"
    else
        # Initialize the database for migrations.
        docker-compose \
            run --rm api-server "mg init"
    fi

    # Run database migrations. The way scala-forklift works requires this to be called twice:
    # the first run figures out the migrations to run and the second run applies them.
    docker-compose \
        run --rm api-server "mg update"
    docker-compose \
        run --rm api-server "mg apply"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Updating Scala dependencies"
        docker-compose up -d api-server

        docker-compose exec -T api-server ./sbt update
        docker-compose rm -sf api-server

        echo "Running application database migrations"
        run_database_migrations

        echo "Building static asset bundle"
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend install
        docker-compose \
            -f "${DIR}/../docker-compose.yml" \
            -f "${DIR}/../docker-compose.test.yml" \
            run --rm app-frontend run build
    fi
    exit
fi
