---
- name: Install application Python dependencies for development and test
  pip: chdir={{ app_home }}/requirements requirements={{ item }}.txt
  with_items:
    - development
    - test
  when: "['development', 'test'] | some_are_in(group_names)"
  notify:
    - Restart rf-app

- name: Install application Python dependencies for production
  pip: chdir="{{ app_home }}/requirements" requirements=production.txt
  when: "['packer'] | is_in(group_names)"
  notify:
    - Restart rf-app
