---
- name: Install Docker Compose
  pip: name=docker-compose version={{ docker_compose_version }}

- name: Add Ansible user to Docker group
  user: name="{{ item }}"
        groups=docker
        append=yes
  with_items: "{{ docker_users }}"

- name: Install Docker Daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Docker
