---
- hosts: services
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "raster-foundry.postgresql", when: "['development', 'test'] | some_are_in(group_names)" }
    - { role: "raster-foundry.pgweb", when: "['development', 'test'] | some_are_in(group_names)" }
    - { role: "azavea.redis", when: "['development', 'test'] | some_are_in(group_names)" }

    - { role: "raster-foundry.graphite", when: "['test'] | is_not_in(group_names)" }
    - { role: "raster-foundry.logstash", when: "['test'] | is_not_in(group_names)" }
    - { role: "azavea.kibana", when: "['test'] | is_not_in(group_names)" }
